server:
  port: 9090
spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL55Dialect
      connection:
        CharSet: UTF-8
        characterEncoding: UTF-8
        useUnicode: true
  datasource:
    url: jdbc:mysql://localhost:13306/tacocloud?useUnicode=yes&characterEncoding=utf-8
    username: tacodb
    password: tacopassword
  data:
    rest:
      base-path: /data
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: 13tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tacoweb
    password: 13tm31n
    template:
      receive-timeout: 3000
      # exchange: tacocloud.orders
      # routing-key: kitchens.central
logging:
  level:
    root: WARN
    love.lipbcu.taco: DEBUG
    love.lipbcu.tacocloud: DEBUG
love.lipbcu.taco:
  orders.pageSize: 5
